import propTypes from 'prop-types'
import { Inter } from 'next/font/google'

import '../../node_modules/minireset.css/minireset.min.css'
import './globals.css'
import { Header } from './components/organisms/ui/header/Header'
import { Footer } from './components/organisms/ui/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  )
}

RootLayout.propTypes = {
  children: propTypes.node,
}
